spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true
    username: sa
    password: password
  datasource2:
    url: jdbc:oracle:thin:@//localhost:1521
    username: SYSTEM
    password: password
logging:
  level:
    com.example.demo.mapper: trace
